name: parking_booking_system
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  intl: ^0.17.0
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  google_maps_flutter: ^2.9.0
  twilio_flutter: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  mailer: ^6.2.0

flutter:
  uses-material-design: true

  # Add your image assets here
  assets:
    - assets/Park.png
    - assets/dr.png
    - assets/dr1.png
