import 'package:hive/hive.dart';

part 'parking_location.g.dart'; // This will be generated by Hive

@HiveType(typeId: 1) // Unique ID for the adapter
class ParkingLocation extends HiveObject{
  @HiveField(0) // Field index for ID
  final String id;

  @HiveField(1) // Field index for name
  final String name;

  @HiveField(2) // Field index for address
  final String address;

  @HiveField(3) // Field index for status
  final String status;

  @HiveField(4) // Field index for price
  final double price; // Price as a double

  @HiveField(5) // Field index for latitude
  final double latitude; // Latitude as a double

  @HiveField(6) // Field index for longitude
  final double longitude; // Longitude as a double

  @HiveField(7) // Add a new field for pricePerHour
  final double? pricePerHour; 

  ParkingLocation({
    required this.id,
    required this.name,
    required this.address,
    required this.status,
    required this.price, 
    required this.latitude, 
    required this.longitude,
    this.pricePerHour, 
  });
}
