import 'package:hive/hive.dart';

part 'vehicle.g.dart'; // Generated by Hive

@HiveType(typeId: 0)
class Vehicle extends HiveObject {
  @HiveField(0)
  final String driverName;
  
  @HiveField(1)
  final String driverPhone;

  @HiveField(2)
  final String vehicleType;

  @HiveField(3)
  final String licensePlate;

  @HiveField(4)
  final String ticketID;

  Vehicle({
    required this.driverName,
    required this.driverPhone,
    required this.vehicleType,
    required this.licensePlate,
    required this.ticketID,
  });
}
