// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTgFK8T2BrJRaDTbzjo8XdniB82naeWEg',
    appId: '1:996583440960:web:4b31e1d685d8d9c9a8d5a5',
    messagingSenderId: '996583440960',
    projectId: 'parking-booking-app-71322',
    authDomain: 'parking-booking-app-71322.firebaseapp.com',
    databaseURL: 'https://parking-booking-app-71322-default-rtdb.firebaseio.com',
    storageBucket: 'parking-booking-app-71322.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAttjwaE27GH72nT55WRTVbr7bfgj9f-4M',
    appId: '1:996583440960:ios:095bf3f9cea81cc6a8d5a5',
    messagingSenderId: '996583440960',
    projectId: 'parking-booking-app-71322',
    databaseURL: 'https://parking-booking-app-71322-default-rtdb.firebaseio.com',
    storageBucket: 'parking-booking-app-71322.appspot.com',
    iosBundleId: 'com.example.parkingBookingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTgFK8T2BrJRaDTbzjo8XdniB82naeWEg',
    appId: '1:996583440960:web:124a19f242e92ca8a8d5a5',
    messagingSenderId: '996583440960',
    projectId: 'parking-booking-app-71322',
    authDomain: 'parking-booking-app-71322.firebaseapp.com',
    databaseURL: 'https://parking-booking-app-71322-default-rtdb.firebaseio.com',
    storageBucket: 'parking-booking-app-71322.appspot.com',
  );
}
